# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:

    runs-on: ubuntu-latest
    container: setsoft/kicad_pybuild:latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        KICOST_RELEASE: 1
      run: |
        apt-get -y update
        apt-get -y install --no-install-recommends python3-bs4 python3-future python3-lxml python3-requests python3-tqdm wget python3-pip python3-xlsxwriter
        python3 setup.py sdist bdist_wheel
        twine upload dist/*
